launch=gmysql
gmysql-host=powerdns-db
gmysql-port=3306
gmysql-dbname=powerdns
gmysql-user=powerdns
gmysql-password=powerdns
api=yes
api-key=zonix-dev-powerdns-key
webserver=yes
webserver-address=0.0.0.0
webserver-port=8081
webserver-allow-from=0.0.0.0/0,::/0
local-address=0.0.0.0
local-port=5300
disable-syslog=yes
loglevel=9
webserver-loglevel=detailed
