setuid=pdns
setgid=pdns
launch=gsqlite3
gsqlite3-database=/var/lib/powerdns/pdns.sqlite3
api=yes
api-key=zonix-dev-powerdns-key
webserver=yes
webserver-address=0.0.0.0
webserver-port=8081
webserver-allow-from=0.0.0.0/0,::/0
local-address=0.0.0.0
local-port=5300
disable-syslog=yes
