apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zonix.fullname" . }}-backend-secret
  labels:
    {{- include "zonix.labels" . | nindent 4 }}
type: Opaque
stringData:
  ZONIX_DATABASE_URL: {{ .Values.backend.secretEnv.databaseUrl | quote }}
  ZONIX_BOOTSTRAP_ADMIN_PASSWORD: {{ .Values.backend.secretEnv.bootstrapAdminPassword | quote }}
  ZONIX_SESSION_SECRET_KEY: {{ .Values.backend.secretEnv.sessionSecretKey | quote }}
  ZONIX_OIDC_BOOTSTRAP_CLIENT_SECRET: {{ .Values.backend.secretEnv.oidcBootstrapClientSecret | quote }}
  ZONIX_POWERDNS_API_KEY: {{ .Values.backend.secretEnv.powerdnsApiKey | quote }}
  ZONIX_BIND_TSIG_SECRET: {{ .Values.backend.secretEnv.bindTsigSecret | quote }}
