apiVersion: v1
kind: Service
metadata:
  name: {{ include "zonix.fullname" . }}-frontend
  labels:
    {{- include "zonix.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "zonix.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
