include "/etc/bind/zonix-key.conf";

options {
    directory "/var/cache/bind";
    listen-on port 53 { any; };
    listen-on-v6 { none; };
    recursion no;
    allow-query { any; };
    allow-transfer { none; };
    dnssec-validation no;
    pid-file "/tmp/named.pid";
    session-keyfile "/tmp/session.key";
};

zone "lab.example" IN {
    type master;
    file "/var/lib/bind/zones/lab.example.zone";
    journal "/var/lib/bind/zones/lab.example.zone.jnl";
    allow-transfer { key "zonix-key."; };
    update-policy { grant zonix-key. zonesub ANY; };
    notify no;
};
